/**
 * The shared procedural art foundation for КОРОВАНЫ.
 *
 * Import from here and nowhere deeper: this barrel is the stable surface the NPC
 * and world-object passes build on. See `docs/08-graphics-foundation-spec.md` for
 * the contract, the budgets and the lifecycle rules.
 *
 * The whole module depends on `three`, `three/addons` and `src/game/random/` only.
 * It never reaches back into `GameEngine` or `world/`, and it stays importable from
 * a Node test with no DOM.
 */

export {
  fbm3,
  hashInt3,
  hashUnit,
  hashUnit3,
  ridgeNoise3,
  valueNoise3,
} from './ArtNoise.ts'

export {
  artNoiseSeed,
  artVariation,
  createArtStream,
  wrapArtVariation,
  type ArtVariation,
} from './ArtRandom.ts'

// `RandomStream` and `SeedInput` appear in the signatures above and in §5.2 of the
// spec, so a caller following the documented surface must be able to name them
// from here. Exported as types only, deliberately: `createArtStream` stays the way
// to obtain a stream, and re-exporting the class as a value would invite callers
// to construct one directly and bypass the art namespace.
export type { RandomStream } from '../random/RandomStream.ts'
export type { SeedInput } from '../random/seed.ts'

export {
  OUTLINE_NORMAL_ATTRIBUTE,
  bakeOutlineNormals,
  bakeSkyOcclusion,
  bakeVerticalOcclusion,
  branchStructure,
  displaceGeometry,
  ensureVertexColors,
  extrudeProfile,
  facetGeometry,
  gradientVertexColors,
  hasOutlineNormals,
  latheProfile,
  loftProfile,
  mergeAll,
  paintVertexColors,
  polygonProfile,
  rectProfile,
  stylizedCapsule,
  taperedBox,
  transformed,
  tubeAlongPoints,
  type BranchStructureOptions,
  type DisplaceOptions,
  type ExtrudeProfileOptions,
  type FacetOptions,
  type GradientColorOptions,
  type LatheProfileOptions,
  type LoftOptions,
  type LoftSection,
  type MergeOptions,
  type OutlineNormalOptions,
  type SkyOcclusionOptions,
  type StylizedCapsuleOptions,
  type TaperedBoxOptions,
  type TransformOptions,
  type TubeOptions,
  type Vec2Like,
  type Vec3Like,
  type VertexPaint,
  type VertexPaintContext,
  type VerticalOcclusionOptions,
} from './GeometryKit.ts'

export {
  GeometryCache,
  clearLod,
  createLod,
  type CreateLodOptions,
  type LodLevel,
} from './GeometryCache.ts'

export {
  StylizedArtLibrary,
  type ContactShadowOptions,
  type OutlineBinding,
  type OutlineKind,
  type OutlineOptions,
  type StylizedAdoptOptions,
  type StylizedArtLibraryOptions,
  type StylizedInkPalette,
  type StylizedMaterialOptions,
  type StylizedSurface,
} from './StylizedArtLibrary.ts'

export { hasStylizedShader } from './stylizedShader.ts'

// --- CharacterKit ---
// Wave 2A. People, animals and the caravan: the taxonomy plus every builder that
// turns it into geometry. See `docs/09-npc-and-creature-models-spec.md`.
export {
  BEAST_RIG,
  CHARACTER_DETAIL_DISTANCE,
  CHARACTER_VARIANTS,
  WAGON_RIG,
  buildBeastBody,
  buildBeastHead,
  buildBeastLimb,
  buildBeastTail,
  buildBirdBody,
  buildBirdWing,
  buildCharacterSkeleton,
  buildCloak,
  buildDeerBody,
  buildDeerCrown,
  buildDeerLeg,
  buildFace,
  buildForearm,
  buildHair,
  buildHand,
  buildHarness,
  buildHead,
  buildHeadgear,
  buildOffhand,
  buildOxBody,
  buildOxHead,
  buildShin,
  buildThigh,
  buildTorso,
  buildTorsoTrim,
  buildUpperArm,
  buildWagonAxle,
  buildWagonBed,
  buildWagonCargo,
  buildWagonFrame,
  buildWagonTilt,
  buildWagonWheel,
  buildWeaponGrip,
  buildWeaponHead,
  buildWristRope,
  characterKitForRole,
  characterPartKeys,
  cloakVariant,
  forearmVariant,
  resolveCharacterPlan,
  shinVariant,
  solveHandOffset,
  thighVariant,
  upperArmVariant,
  type ArmourWeight,
  type BeastKind,
  type BeastRig,
  type CharacterFaction,
  type CharacterKitId,
  type CharacterPartKeys,
  type CharacterPlan,
  type CharacterProportions,
  type CharacterSkeleton,
  type CloakKind,
  type HairKind,
  type HeadgearKind,
  type OffhandKind,
  type TorsoClass,
  type TrimKind,
  type WeaponKind,
} from './CharacterKit.ts'

// --- PropKit ---
// The world-object vocabulary. Buildings, settlement dressing, vegetation species,
// rock features and infrastructure. See `docs/10-world-objects-and-props-spec.md`.
export {
  PROP_SURFACES,
  bannerParts,
  barrelGeometry,
  bridgeParts,
  brazierParts,
  buildingParts,
  bushGeometry,
  cairnGeometry,
  cartParts,
  chestParts,
  crateGeometry,
  curtainWallParts,
  deadfallGeometry,
  fencePanelParts,
  gateParts,
  groundCoverGeometry,
  haystackParts,
  lanternPostParts,
  marketStallParts,
  mergePropParts,
  monumentParts,
  obeliskParts,
  outcropGeometry,
  pillarParts,
  propPart,
  reedClusterGeometry,
  screeGeometry,
  shrineParts,
  signboardParts,
  strataRockGeometry,
  stumpGeometry,
  tentParts,
  towerParts,
  transformParts,
  treeGeometry,
  washingLineParts,
  waystoneParts,
  wellParts,
  woodpileGeometry,
  type BannerOptions,
  type BridgeOptions,
  type BuildingOptions,
  type BuildingPalette,
  type CurtainWallOptions,
  type FenceOptions,
  type FenceStyle,
  type GateOptions,
  type GroundCoverKind,
  type GroundCoverOptions,
  type GroundCoverPalette,
  type MergedPropSurface,
  type MonumentOptions,
  type PropOptions,
  type PropPalette,
  type PropPart,
  type PropSurface,
  type RockOptions,
  type RockPalette,
  type RoofStyle,
  type StallOptions,
  type TowerOptions,
  type TreeOptions,
  type TreePalette,
  type TreeSpecies,
  type UndergrowthOptions,
  type WallStyle,
  type WellOptions,
} from './PropKit.ts'
